/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import clases.PlayWave;
import java.net.URISyntaxException;
import java.net.URL;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author gerardo
 */
public class FrmPrincipal extends javax.swing.JFrame {

    private JLabel[] tablero = new JLabel[16]; // arreglo para el tablero de imagenes
    private int[] datos = new int[16]; // arreglo para los datos de las imagenes
    private boolean banClick = false; //false = primer click; true = segundo click 
    private int pos1; //posicion del primer tiro
    private int pos2; //posixion del segundo tiro
    private int tipo; // 0= Clasico , 1 = Avanzado
    private int disponible; // casilla vacia
    private boolean banJuego; // indica si el juego a iniciado
    private boolean habilitarTablero; // habilita el tablero

    private JLabel lblTempo = new JLabel(); // temporal para la imagen

    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lblImagen01 = new javax.swing.JLabel();
        lblImagen02 = new javax.swing.JLabel();
        lblImagen03 = new javax.swing.JLabel();
        lblImagen04 = new javax.swing.JLabel();
        lblImagen05 = new javax.swing.JLabel();
        lblImagen06 = new javax.swing.JLabel();
        lblImagen07 = new javax.swing.JLabel();
        lblImagen08 = new javax.swing.JLabel();
        lblImagen09 = new javax.swing.JLabel();
        lblImagen10 = new javax.swing.JLabel();
        lblImagen11 = new javax.swing.JLabel();
        lblImagen12 = new javax.swing.JLabel();
        lblImagen13 = new javax.swing.JLabel();
        lblImagen14 = new javax.swing.JLabel();
        lblImagen15 = new javax.swing.JLabel();
        lblImagen16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbImagen = new javax.swing.JComboBox<>();
        btnMezclar = new javax.swing.JButton();
        btnCreditos = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        rbtnTipoClasico = new javax.swing.JRadioButton();
        rbtnTipoAanzado = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Puzzle V 1.0");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImagen01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a1.jpg"))); // NOI18N
        lblImagen01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        lblImagen01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen01MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen01, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 100, 100));

        lblImagen02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a2.jpg"))); // NOI18N
        lblImagen02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        lblImagen02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen02MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen02, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 100, 100));

        lblImagen03.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a3.jpg"))); // NOI18N
        lblImagen03.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        lblImagen03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen03MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen03, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, 100, 100));

        lblImagen04.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a4.jpg"))); // NOI18N
        lblImagen04.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        lblImagen04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen04MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen04, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 100, 100));

        lblImagen05.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a5.jpg"))); // NOI18N
        lblImagen05.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        lblImagen05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen05MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen05, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, 100));

        lblImagen06.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a6.jpg"))); // NOI18N
        lblImagen06.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        lblImagen06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen06MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen06, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 110, 100, 100));

        lblImagen07.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a7.jpg"))); // NOI18N
        lblImagen07.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        lblImagen07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen07MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen07, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 100, 100));

        lblImagen08.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a8.jpg"))); // NOI18N
        lblImagen08.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        lblImagen08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen08MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen08, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 100, 100));

        lblImagen09.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a9.jpg"))); // NOI18N
        lblImagen09.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        lblImagen09.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen09MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen09, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 100, 100));

        lblImagen10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a10.jpg"))); // NOI18N
        lblImagen10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        lblImagen10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen10MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, 100, 100));

        lblImagen11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a11.jpg"))); // NOI18N
        lblImagen11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        lblImagen11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen11MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 100, 100));

        lblImagen12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a12.jpg"))); // NOI18N
        lblImagen12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        lblImagen12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen12MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen12, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 100, 100));

        lblImagen13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a13.jpg"))); // NOI18N
        lblImagen13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        lblImagen13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen13MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 100, 100));

        lblImagen14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a14.jpg"))); // NOI18N
        lblImagen14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        lblImagen14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen14MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen14, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 100, 100));

        lblImagen15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a15.jpg"))); // NOI18N
        lblImagen15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        lblImagen15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen15MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen15, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 100, 100));

        lblImagen16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/a16.jpg"))); // NOI18N
        lblImagen16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240)));
        lblImagen16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblImagen16MouseClicked(evt);
            }
        });
        jPanel1.add(lblImagen16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 100, 100));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Imagen: ");

        cmbImagen.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cmbImagen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Android", "Mario Bros", "Sombrerero", "Muñecas ", "Payaso", "numeros" }));
        cmbImagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbImagenActionPerformed(evt);
            }
        });

        btnMezclar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMezclar.setText("Mezclar");
        btnMezclar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMezclarMouseClicked(evt);
            }
        });
        btnMezclar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMezclarActionPerformed(evt);
            }
        });

        btnCreditos.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnCreditos.setText("Creditos");
        btnCreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditosActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Tipo:");

        buttonGroup1.add(rbtnTipoClasico);
        rbtnTipoClasico.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbtnTipoClasico.setSelected(true);
        rbtnTipoClasico.setText("Clasico");
        rbtnTipoClasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTipoClasicoActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnTipoAanzado);
        rbtnTipoAanzado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbtnTipoAanzado.setText("Avanzado");
        rbtnTipoAanzado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnTipoAanzadoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbImagen, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 28, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(48, 48, 48))
                    .addComponent(btnMezclar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCreditos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnTipoAanzado)
                    .addComponent(rbtnTipoClasico)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(cmbImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnTipoClasico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbtnTipoAanzado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMezclar)
                .addGap(47, 47, 47)
                .addComponent(btnCreditos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir)
                .addGap(44, 44, 44))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * cambia las imagenes segun la seleccion
     * @param evt 
     */
    private void cmbImagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbImagenActionPerformed
        // TODO add your handling code here:
        int op;
        op = cmbImagen.getSelectedIndex();
        rbtnTipoAanzado.setEnabled(true);
//        rbtnTipoClasico.setSelected(true);
        rbtnTipoClasico.setEnabled(true);

        switch (op) {

            case 0:
                tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/a1.jpg")));
                tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/a2.jpg")));
                tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/a3.jpg")));
                tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/a4.jpg")));
                tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/a5.jpg")));
                tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/a6.jpg")));
                tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/a7.jpg")));
                tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/a8.jpg")));
                tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/a9.jpg")));
                tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/a10.jpg")));

                tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/a11.jpg")));
                tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/a12.jpg")));
                tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/a13.jpg")));
                tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/a14.jpg")));
                tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/a15.jpg")));
                tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/a16.jpg")));
                break;

            case 1:
                tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/m1.jpg")));
                tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/m2.jpg")));
                tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/m3.jpg")));
                tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/m4.jpg")));
                tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/m5.jpg")));
                tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/m6.jpg")));
                tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/m7.jpg")));
                tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/m8.jpg")));
                tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/m9.jpg")));
                tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/m10.jpg")));

                tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/m11.jpg")));
                tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/m12.jpg")));
                tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/m13.jpg")));
                tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/m14.jpg")));
                tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/m15.jpg")));
                tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/m16.jpg")));
                break;

            case 2:
                tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/s1.png")));
                tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/s2.png")));
                tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/s3.png")));
                tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/s4.png")));
                tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/s5.png")));
                tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/s6.png")));
                tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/s7.png")));
                tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/s8.png")));
                tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/s9.png")));
                tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/s10.png")));

                tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/s11.png")));
                tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/s12.png")));
                tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/s13.png")));
                tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/s14.png")));
                tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/s15.png")));
                tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/s16.png")));
                break;
            case 3:
                tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/f1.jpg")));
                tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/f2.jpg")));
                tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/f3.jpg")));
                tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/f4.jpg")));
                tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/f5.jpg")));
                tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/f6.jpg")));
                tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/f7.jpg")));
                tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/f8.jpg")));
                tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/f9.jpg")));
                tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/f10.jpg")));

                tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/f11.jpg")));
                tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/f12.jpg")));
                tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/f13.jpg")));
                tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/f14.jpg")));
                tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/f15.jpg")));
                tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/f16.jpg")));
                break;

            case 4:
                tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/p1.jpg")));
                tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/p2.jpg")));
                tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/p3.jpg")));
                tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/p4.jpg")));
                tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/p5.jpg")));
                tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/p6.jpg")));
                tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/p7.jpg")));
                tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/p8.jpg")));
                tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/p9.jpg")));
                tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/p10.jpg")));

                tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/p11.jpg")));
                tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/p12.jpg")));
                tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/p13.jpg")));
                tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/p14.jpg")));
                tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/p15.jpg")));
                tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/p16.jpg")));
                break;

            case 5:
                tablero[0].setIcon(new ImageIcon(getClass().getResource("/imagenes/n1.png")));
                tablero[1].setIcon(new ImageIcon(getClass().getResource("/imagenes/n2.png")));
                tablero[2].setIcon(new ImageIcon(getClass().getResource("/imagenes/n3.png")));
                tablero[3].setIcon(new ImageIcon(getClass().getResource("/imagenes/n4.png")));
                tablero[4].setIcon(new ImageIcon(getClass().getResource("/imagenes/n5.png")));
                tablero[5].setIcon(new ImageIcon(getClass().getResource("/imagenes/n6.png")));
                tablero[6].setIcon(new ImageIcon(getClass().getResource("/imagenes/n7.png")));
                tablero[7].setIcon(new ImageIcon(getClass().getResource("/imagenes/n8.png")));
                tablero[8].setIcon(new ImageIcon(getClass().getResource("/imagenes/n9.png")));
                tablero[9].setIcon(new ImageIcon(getClass().getResource("/imagenes/n10.png")));

                tablero[10].setIcon(new ImageIcon(getClass().getResource("/imagenes/n11.png")));
                tablero[11].setIcon(new ImageIcon(getClass().getResource("/imagenes/n12.png")));
                tablero[12].setIcon(new ImageIcon(getClass().getResource("/imagenes/n13.png")));
                tablero[13].setIcon(new ImageIcon(getClass().getResource("/imagenes/n14.png")));
                tablero[14].setIcon(new ImageIcon(getClass().getResource("/imagenes/n15.png")));
                tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/n16.png")));
                break;
            default:
                JOptionPane.showMessageDialog(this, "opcion no valida");
        }
    }//GEN-LAST:event_cmbImagenActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        /**
         * 
         */
        // TODO add your handling code here:
        tablero[0] = lblImagen01;
        tablero[1] = lblImagen02;
        tablero[2] = lblImagen03;
        tablero[3] = lblImagen04;
        tablero[4] = lblImagen05;
        tablero[5] = lblImagen06;
        tablero[6] = lblImagen07;
        tablero[7] = lblImagen08;
        tablero[8] = lblImagen09;
        tablero[9] = lblImagen10;
        tablero[10] = lblImagen11;
        tablero[11] = lblImagen12;
        tablero[12] = lblImagen13;
        tablero[13] = lblImagen14;
        tablero[14] = lblImagen15;
        tablero[15] = lblImagen16;

        for (int i = 0; i < 16; i++) {
            datos[i] = i;
        }


    }//GEN-LAST:event_formWindowOpened

    private void lblImagen01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen01MouseClicked

        // TODO add your handling code here:
        tirar(0);

    }//GEN-LAST:event_lblImagen01MouseClicked

    private void lblImagen02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen02MouseClicked

        // TODO add your handling code here:
        tirar(1);
    }//GEN-LAST:event_lblImagen02MouseClicked

    private void lblImagen03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen03MouseClicked

        // TODO add your handling code here:
        tirar(2);
    }//GEN-LAST:event_lblImagen03MouseClicked

    private void lblImagen04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen04MouseClicked

        // TODO add your handling code here:
        tirar(3);
    }//GEN-LAST:event_lblImagen04MouseClicked

    private void lblImagen05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen05MouseClicked

        // TODO add your handling code here:
        tirar(4);
    }//GEN-LAST:event_lblImagen05MouseClicked

    private void lblImagen06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen06MouseClicked

        // TODO add your handling code here:
        tirar(5);
    }//GEN-LAST:event_lblImagen06MouseClicked

    private void btnMezclarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMezclarMouseClicked

        // TODO add your handling code here:

    }//GEN-LAST:event_btnMezclarMouseClicked

    /**
     * mezcla las imagenes en todo el tablero
     * @param evt 
     */
    private void btnMezclarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMezclarActionPerformed

        explosion();
        habilitarTablero = true;
        if (rbtnTipoClasico.isSelected()) {
            tipo = 0;
        }

        JOptionPane.showMessageDialog(this, "puedes iniciar, ¡Mucha Suerte!");
        // TODO add your handling code here:
        Random r1 = new Random();
        int x;
        int y;
        if (tipo == 0) {
            for (int i = 0; i < 500; i++) {
                x = r1.nextInt(16);
                y = r1.nextInt(16);
                seleccionar(x);
                seleccionar(y);
            }
        } else if (tipo == 1) {

            for (int i = 0; i < 500; i++) {

                y = r1.nextInt(16);
                tirar(y);
            }

        }

        rbtnTipoAanzado.setEnabled(false);
        rbtnTipoClasico.setEnabled(false);
        cmbImagen.setEnabled(false);

        banJuego = true;

        // btnMezclar.setEnabled(false);

    }//GEN-LAST:event_btnMezclarActionPerformed

    private void lblImagen07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen07MouseClicked

        // TODO add your handling code here:
        tirar(6);
    }//GEN-LAST:event_lblImagen07MouseClicked

    private void lblImagen08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen08MouseClicked

        // TODO add your handling code here:
        tirar(7);
    }//GEN-LAST:event_lblImagen08MouseClicked

    private void lblImagen09MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen09MouseClicked

        // TODO add your handling code here:
        tirar(8);
    }//GEN-LAST:event_lblImagen09MouseClicked

    private void lblImagen10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen10MouseClicked

        // TODO add your handling code here:
        tirar(9);
    }//GEN-LAST:event_lblImagen10MouseClicked

    private void lblImagen11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen11MouseClicked

        // TODO add your handling code here:
        tirar(10);
    }//GEN-LAST:event_lblImagen11MouseClicked

    private void lblImagen12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen12MouseClicked

        // TODO add your handling code here:
        tirar(11);
    }//GEN-LAST:event_lblImagen12MouseClicked

    private void lblImagen13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen13MouseClicked

        // TODO add your handling code here:
        tirar(12);
    }//GEN-LAST:event_lblImagen13MouseClicked

    private void lblImagen14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen14MouseClicked

        // TODO add your handling code here:
        tirar(13);
    }//GEN-LAST:event_lblImagen14MouseClicked

    private void lblImagen15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen15MouseClicked

        // TODO add your handling code here:
        tirar(14);
    }//GEN-LAST:event_lblImagen15MouseClicked

    private void lblImagen16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblImagen16MouseClicked

        // TODO add your handling code here:
        tirar(15);
    }//GEN-LAST:event_lblImagen16MouseClicked

    /**
     * salir del juego
     * @param evt 
     */
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed

        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * manda datos en un mensaje
     * @param evt 
     */
    private void btnCreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditosActionPerformed

        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Este juego es una idea original"
                + " de: \n  Apolinar Trejo Cuevas \n Desarrollado por:"
                + "\n Juan Gerardo  Andrade Ortiz \n UTNG \n GSI1331 \n DESARROLLO APLICACIONES I");

    }//GEN-LAST:event_btnCreditosActionPerformed

    /**
     * cambia el modo del juego a avanzado
     * @param evt 
     */
    private void rbtnTipoAanzadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTipoAanzadoActionPerformed
        // TODO add your handling code here:
        tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/vacia.jpg")));
        tipo = 1; // Avanzado
        disponible = 15; //<-------------
        // banClick=false;

    }//GEN-LAST:event_rbtnTipoAanzadoActionPerformed

    /**
     * pone el modo del juego en clasico
     * @param evt 
     */
    private void rbtnTipoClasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnTipoClasicoActionPerformed

        // TODO add your handling code here:
        switch (cmbImagen.getSelectedIndex()) {
            case 0:
                tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/a16.jpg")));
                break;
            case 1:
                tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/m16.jpg")));
                break;
            case 2:
                tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/s16.png")));
                break;
            case 3:
                tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/f16.jpg")));
                break;
            case 4:
                tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/p16.jpg")));
                break;

        }
        tipo = 0;
    }//GEN-LAST:event_rbtnTipoClasicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    /**
     * selecciona la imagen del arreglo, y las intercambia
     * @param pos 
     */
    private void seleccionar(int pos) {
        

        if (!banClick) {
            tablero[pos].setBorder(javax.swing.BorderFactory.createLineBorder(
                    new java.awt.Color(255, 0, 0)));
            pos1 = pos;
            banClick = true;
        } else {
            pos2 = pos;
            tablero[pos1].setBorder(javax.swing.BorderFactory.createLineBorder(
                    new java.awt.Color(0, 0, 0)));

            banClick = false;
            // Moviendo las imagenes 
            lblTempo.setIcon(tablero[pos1].getIcon());
            tablero[pos1].setIcon(tablero[pos2].getIcon());
            tablero[pos2].setIcon(lblTempo.getIcon());

            //moviendo los datos
            int tempo;
            tempo = datos[pos1];
            datos[pos1] = datos[pos2];
            datos[pos2] = tempo;
        }

    }

    /**
     * manda resultado si se ha ganado
     * @return 
     */
    public boolean yaGano() {

        for (int i = 0; i < 16; i++) {
            if (datos[i] != i) {
                return false;
            }
        }

        // banJuego=false;
        rbtnTipoAanzado.setEnabled(true);
        rbtnTipoClasico.setEnabled(true);
        return true;

    }

    /**
     * hace la accion de tirar utilizando seleccionar
     * @param pos 
     */
    public void tirar(int pos) {

        if (tipo == 1 && validarTiro(pos)) {

            if (habilitarTablero) {
                seleccionar(disponible);
                seleccionar(pos);
                disponible = pos;
            }
            verificar();

        }
        if (tipo == 0) {
            if (habilitarTablero) {
                seleccionar(pos);
                verificar();
            }
        }

    }

    /**
     * analiza si estan en orden todas las condiciones del juego para
     * ganar
     */
    public void verificar() {

        if (banJuego && !banClick && yaGano()) {
            exclamacion();
            JOptionPane.showMessageDialog(this, "ya Ganaste Campeón!");
            habilitarTablero = false;
            

            pos1 = 0;
            pos2 = 0;
            banJuego = false;
            cmbImagen.setEnabled(true);
            switch (cmbImagen.getSelectedIndex()) {
                case 0:
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/a16.jpg")));
                    break;
                case 1:
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/m16.jpg")));
                    break;
                case 2:
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/s16.png")));
                    break;
                case 3:
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/f16.jpg")));
                    break;
                case 4:
                    tablero[15].setIcon(new ImageIcon(getClass().getResource("/imagenes/p16.jpg")));
                    break;

            }
            rbtnTipoClasico.setSelected(true);
//            this.rbtnTipoClasicoActionPerformed(null);

        }

    }

    /**
     * valida el tiro si se encuentra en modo avanzado
     * @param pos
     * @return 
     */
    public boolean validarTiro(int pos) {
        // se valida si pertencen a la misma fila y estan  a una casilla de distancia
        if (disponible / 4 == pos / 4 && Math.abs(pos - disponible) == 1) {

            return true;
        }
        // se valida si pertenece a la misma columna y estan a 4 casillas de distancia
        if (disponible % 4 == pos % 4 && Math.abs(pos - disponible) == 4) {
            return true;
        }
        return false;
    }

    /**
     * sonido de explosion
     */
    public void explosion() {
        try {

            PlayWave pw1;
            String url = "/media/explos.wav";
            pw1 = new PlayWave(url);
            pw1.start();
        } catch (Exception e) {
            System.out.println("error en la sintaxis del archivo");
        }
    }

    /**
     * sonido de exclamacion
     */
    public void exclamacion() {
        try {

            PlayWave pw1;
            String url = "/media/wow.wav";
            pw1 = new PlayWave(url);
            pw1.start();
        } catch (Exception e) {
            System.out.println("error en la sintaxis del archivo");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreditos;
    private javax.swing.JButton btnMezclar;
    private javax.swing.JButton btnSalir;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbImagen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblImagen01;
    private javax.swing.JLabel lblImagen02;
    private javax.swing.JLabel lblImagen03;
    private javax.swing.JLabel lblImagen04;
    private javax.swing.JLabel lblImagen05;
    private javax.swing.JLabel lblImagen06;
    private javax.swing.JLabel lblImagen07;
    private javax.swing.JLabel lblImagen08;
    private javax.swing.JLabel lblImagen09;
    private javax.swing.JLabel lblImagen10;
    private javax.swing.JLabel lblImagen11;
    private javax.swing.JLabel lblImagen12;
    private javax.swing.JLabel lblImagen13;
    private javax.swing.JLabel lblImagen14;
    private javax.swing.JLabel lblImagen15;
    private javax.swing.JLabel lblImagen16;
    private javax.swing.JRadioButton rbtnTipoAanzado;
    private javax.swing.JRadioButton rbtnTipoClasico;
    // End of variables declaration//GEN-END:variables
}
